const places=[
[1,"Lake Coatepeque","Lago de Coatepeque","Water","Santa Ana","El Congo",13.866,-89.55,"🌊","A volcanic crater lake with blue water, restaurants, boat rides and unforgettable sunsets.","Lago volcánico de agua azul, restaurantes, paseos en lancha y atardeceres inolvidables."],
[2,"Santa Ana Volcano","Volcán de Santa Ana","Nature","Santa Ana","Santa Ana",13.853,-89.63,"🌋","Hike to El Salvador's highest volcano and its turquoise crater lake.","Sube al volcán más alto de El Salvador y contempla su laguna turquesa."],
[3,"El Tunco","El Tunco","Water","La Libertad","Tamanique",13.494,-89.382,"🏄","Iconic surf village known for waves, sunsets, restaurants and nightlife.","Pueblo surfista famoso por sus olas, atardeceres, restaurantes y vida nocturna."],
[4,"El Boquerón","El Boquerón","Nature","San Salvador","San Salvador",13.735,-89.286,"🥾","A cool mountain escape with an accessible trail overlooking a vast crater.","Escape de montaña con un sendero accesible y vista a un enorme cráter."],
[5,"Historic Center","Centro Histórico","Culture","San Salvador","San Salvador",13.698,-89.191,"🏛️","Landmarks, plazas, markets and the National Palace in the revitalized capital center.","Monumentos, plazas, mercados y el Palacio Nacional en el renovado centro capitalino."],
[6,"Suchitoto","Suchitoto","Town","Cuscatlán","Suchitoto",13.938,-89.027,"⛪","A cobblestone colonial town filled with art, history and lake views.","Ciudad colonial de calles empedradas, arte, historia y vistas al lago."],
[7,"Conchagua Volcano","Volcán de Conchagua","Activity","La Unión","Conchagua",13.276,-87.845,"⛺","Camp above the Gulf of Fonseca for sunrise views across volcanic islands.","Acampa sobre el golfo de Fonseca con vistas a islas volcánicas al amanecer."],
[8,"Río Sapo","Río Sapo","Water","Morazán","Arambala",13.944,-88.12,"💧","Turquoise water, pine forest and quiet natural pools in eastern El Salvador.","Agua turquesa, bosque de pinos y pozas naturales en el oriente del país."],
[9,"El Mozote Memorial","Memorial El Mozote","Culture","Morazán","Meanguera",13.944,-88.044,"🕊️","An important memorial and place of reflection on civil-war history.","Importante memorial y espacio de reflexión sobre la historia de la guerra civil."],
[10,"Alegría Lagoon","Laguna de Alegría","Nature","Usulután","Alegría",13.494,-88.493,"🌿","An emerald volcanic lagoon beside a charming highland town.","Laguna volcánica esmeralda junto a un encantador pueblo de montaña."],
[11,"El Cuco Beach","Playa El Cuco","Water","San Miguel","Chirilagua",13.171,-88.106,"🏖️","A long relaxed beach and gateway to the Wild East coast.","Playa extensa y tranquila, puerta de entrada al oriente salvaje."],
[12,"Nahuizalco","Nahuizalco","Town","Sonsonate","Nahuizalco",13.777,-89.737,"🧺","Indigenous heritage, artisan traditions and a distinctive evening market.","Herencia indígena, tradición artesanal y un característico mercado nocturno."],
[13,"Joya de Cerén","Joya de Cerén","Ruins","La Libertad","San Juan Opico",13.827,-89.37,"🏺","A UNESCO site preserving ancient village life beneath volcanic ash.","Sitio UNESCO que conserva la vida de una antigua aldea bajo ceniza volcánica."],
[14,"Los Cóbanos","Los Cóbanos","Water","Sonsonate","Acajutla",13.527,-89.802,"🐠","A reef coast for snorkeling, diving, seafood and whale watching.","Costa de arrecife para esnórquel, buceo, mariscos y avistamiento de ballenas."],
[15,"Pupusa Route","Ruta de las Pupusas","Coffee / Food","San Salvador","Panchimalco",13.646,-89.19,"🫓","Taste the national dish in the lively pupuserías of Planes de Renderos.","Prueba el plato nacional en las animadas pupuserías de Planes de Renderos."],
[16,"Ataco","Concepción de Ataco","Town","Ahuachapán","Ataco",13.87,-89.848,"🎨","Murals, coffee, cool weather and weekend energy on the Ruta de las Flores.","Murales, café, clima fresco y ambiente de fin de semana en la Ruta de las Flores."],
[17,"Montecristo Park","Parque Montecristo","Nature","Santa Ana","Metapán",14.397,-89.386,"🌲","Cloud forest, orchids and mountain trails at the meeting point of three countries.","Bosque nebuloso, orquídeas y senderos en el encuentro de tres países."],
[18,"Gulf of Fonseca","Golfo de Fonseca","Activity","La Unión","La Unión",13.31,-87.754,"⛵","Boat among volcanic islands, fishing communities and dramatic scenery.","Navega entre islas volcánicas, comunidades pesqueras y paisajes espectaculares."],
[19,"El Salvador International Airport","Aeropuerto Internacional de El Salvador","Airport","La Paz","San Luis Talpa",13.4409,-89.0557,"✈️","The country's main international gateway, officially named Monseñor Óscar Arnulfo Romero International Airport, about 40 kilometers from San Salvador.","La principal entrada aérea del país, oficialmente Aeropuerto Internacional Monseñor Óscar Arnulfo Romero, aproximadamente a 40 kilómetros de San Salvador."],
[20,"Tazumal","Tazumal","Ruins","Santa Ana","Chalchuapa",13.9794,-89.6742,"🗿","One of El Salvador's most impressive Maya archaeological complexes, with a monumental stepped structure and an on-site museum.","Uno de los complejos arqueológicos mayas más impresionantes de El Salvador, con una estructura monumental escalonada y museo."],
[21,"San Andrés Archaeological Park","Parque Arqueológico San Andrés","Ruins","La Libertad","Ciudad Arce",13.8089,-89.3906,"🏺","A major pre-Hispanic ceremonial and administrative center in the Zapotitán Valley, surrounded by volcanic landscapes.","Importante centro ceremonial y administrativo prehispánico en el valle de Zapotitán, rodeado de paisajes volcánicos."],
[22,"Cihuatán Archaeological Park","Parque Arqueológico Cihuatán","Ruins","San Salvador","Aguilares",13.9659,-89.1722,"🛕","A vast fortified pre-Hispanic city with pyramids, plazas and a ball court north of San Salvador.","Extensa ciudad prehispánica fortificada con pirámides, plazas y cancha de pelota al norte de San Salvador."]
].map(x=>({id:x[0],name:x[1],es:x[2],category:x[3],department:x[4],city:x[5],lat:x[6],lng:x[7],emoji:x[8],description:x[9],descripcion:x[10]}));
const wikiTitles={1:"Lake Coatepeque",2:"Santa Ana Volcano",3:"El Tunco",4:"San Salvador (volcano)",5:"San Salvador",6:"Suchitoto",7:"Conchagua (volcano)",8:"Río Sapo",9:"El Mozote",10:"Lake Alegría",11:"El Cuco",12:"Nahuizalco",13:"Joya de Cerén",14:"Los Cóbanos",15:"Pupusa",16:"Concepción de Ataco",17:"Montecristo Trifinio",18:"Gulf of Fonseca",19:"El Salvador International Airport",20:"Tazumal",21:"San Andrés, El Salvador",22:"Cihuatán"};
async function loadImages(){
 const titleToPlace=new Map(places.map(p=>[wikiTitles[p.id],p]));
 try{
  const titles=[...titleToPlace.keys()].join("|");
  const url="https://en.wikipedia.org/w/api.php?action=query&origin=*&format=json&redirects=1&prop=pageimages|info&inprop=url&pithumbsize=900&titles="+encodeURIComponent(titles);
  const response=await fetch(url);
  const payload=await response.json();
  Object.values(payload.query?.pages||{}).forEach(page=>{
   const place=titleToPlace.get(page.title)||places.find(p=>wikiTitles[p.id]===page.title);
   if(place&&page.thumbnail?.source){place.image=page.thumbnail.source;place.imagePage=page.fullurl}
  });
 }catch(error){console.info("Destination photos unavailable; using category artwork.",error)}
 render();if(selected)openPlace(selected);
}
const tr={en:{explore:"Explore",transport:"Transport",business:"For businesses",kicker:"THE LITTLE COUNTRY WITH A BIG SOUL",title:"Find your next unforgettable place in El Salvador.",intro:"Beaches, volcanoes, colorful towns and incredible food—all on one interactive map made for international travelers.",open:"Explore the map",curated:"curated places",departments:"departments",languages:"languages",plan:"PLAN YOUR TRIP",mapTitle:"Explore places on the map",mapHelp:"Click a marker or place card for details.",reset:"Reset",found:"places found",yourTrip:"YOUR TRIP",save:"Save places as you explore",want:"Want to visit",visited:"Visited",tools:"TRAVEL TOOLS",move:"Everything you need to move around",bus:"Bus guide",busText:"Routes, terminals, estimated fares and travel times.",car:"Rent a car",carText:"Compare trusted options for cities, beaches and rural roads.",esim:"eSIM & data",esimText:"Arrive connected with packages selected for El Salvador.",soon:"COMING SOON",own:"Do you own a place travelers should discover?",ownerText:"Verified profiles, direct contact details and featured map placement are coming soon.",join:"Join partner waitlist",directions:"Directions",footer:"Made for curious travelers.",allCat:"All categories",allDep:"All departments",wantBtn:"♡ Want to visit",wanted:"♥ Want to visit",mark:"✓ Mark visited",done:"✓ Visited",empty:"No places found."},es:{explore:"Explorar",transport:"Transporte",business:"Para negocios",kicker:"EL PULGARCITO CON ALMA GIGANTE",title:"Encuentra tu próximo lugar inolvidable en El Salvador.",intro:"Playas, volcanes, pueblos coloridos y comida increíble, todo en un mapa interactivo para viajeros internacionales.",open:"Explorar el mapa",curated:"lugares seleccionados",departments:"departamentos",languages:"idiomas",plan:"PLANIFICA TU VIAJE",mapTitle:"Explora lugares en el mapa",mapHelp:"Haz clic en un marcador o tarjeta para ver detalles.",reset:"Restablecer",found:"lugares encontrados",yourTrip:"TU VIAJE",save:"Guarda lugares mientras exploras",want:"Quiero visitar",visited:"Visitados",tools:"HERRAMIENTAS DE VIAJE",move:"Todo lo necesario para movilizarte",bus:"Guía de buses",busText:"Rutas, terminales, precios estimados y tiempos de viaje.",car:"Alquilar vehículo",carText:"Compara opciones confiables para ciudad, playa y caminos rurales.",esim:"eSIM y datos",esimText:"Llega conectado con paquetes seleccionados para El Salvador.",soon:"PRÓXIMAMENTE",own:"¿Tienes un lugar que los viajeros deberían descubrir?",ownerText:"Próximamente habrá perfiles verificados, contacto directo y posiciones destacadas.",join:"Unirse a la lista de socios",directions:"Cómo llegar",footer:"Hecho para viajeros curiosos.",allCat:"Todas las categorías",allDep:"Todos los departamentos",wantBtn:"♡ Quiero visitar",wanted:"♥ Quiero visitar",mark:"✓ Marcar visitado",done:"✓ Visitado",empty:"No se encontraron lugares."}};
const colors={"Water":"#1687a7","Nature":"#2d7a4c","Culture":"#b2673c","Town":"#7557a1","Coffee / Food":"#9a603a","Hotel":"#c38b2c","Bar / Club":"#963d67","Activity":"#e25d36","Airport":"#1769aa","Ruins":"#b05f3c"};
const categoryEN={"Water":"Beaches, Lakes & Rivers","Airport":"Airport","Ruins":"Ruins"};
const categoryES={"Water":"Escapadas acuáticas","Nature":"Naturaleza","Culture":"Cultura","Town":"Pueblos y ciudades","Coffee / Food":"Café y comida","Hotel":"Hotel","Bar / Club":"Bares y discotecas","Activity":"Actividades","Airport":"Aeropuerto","Ruins":"Ruinas"};
const categoryLabel=value=>lang==="es"?(categoryES[value]||value):(categoryEN[value]||value);
let lang=localStorage.estgLang||"en",want=new Set(JSON.parse(localStorage.estgWant||"[]")),visited=new Set(JSON.parse(localStorage.estgVisited||"[]")),selected=0,special="";
const map=L.map("map").setView([13.73,-88.87],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);const layer=L.layerGroup().addTo(map);
const t=k=>tr[lang][k]||k;
function persist(){localStorage.estgWant=JSON.stringify([...want]);localStorage.estgVisited=JSON.stringify([...visited]);counts()}
function counts(){wantCount.textContent=want.size;visitedCount.textContent=visited.size}
function fill(){let cv=category.value,dv=department.value;category.innerHTML='<option value="">'+t("allCat")+'</option>'+[...new Set(places.map(p=>p.category))].sort().map(x=>'<option value="'+x+'">'+categoryLabel(x)+'</option>').join("");department.innerHTML='<option value="">'+t("allDep")+'</option>'+[...new Set(places.map(p=>p.department))].sort().map(x=>'<option>'+x+'</option>').join("");category.value=cv;department.value=dv}
function data(){let q=search.value.toLowerCase(),c=category.value,d=department.value;return places.filter(p=>(!q||[p.name,p.es,p.city,p.department].join(" ").toLowerCase().includes(q))&&(!c||p.category===c)&&(!d||p.department===d)&&(!special||(special==="want"?want:visited).has(p.id)))}
function render(){let list=data();layer.clearLayers();count.textContent=list.length;cards.innerHTML=list.map(p=>'<button class="card" data-id="'+p.id+'"><span class="thumb" style="background:'+colors[p.category]+'22">'+(p.image?'<img src="'+p.image+'" alt="" loading="lazy">':'<span>'+p.emoji+'</span>')+'<b class="category-badge">'+p.emoji+'</b></span><span><small>'+categoryLabel(p.category)+'</small><h3>'+(lang==="en"?p.name:p.es)+'</h3><p>'+p.city+' · '+p.department+'</p></span></button>').join("")||'<p style="padding:20px;color:#667169">'+t("empty")+'</p>';list.forEach(p=>{let icon=L.divIcon({className:"",html:'<div class="pin" style="background:'+colors[p.category]+'"><span>'+p.emoji+'</span></div>',iconSize:[38,38],iconAnchor:[19,38]});L.marker([p.lat,p.lng],{icon}).addTo(layer).on("click",()=>openPlace(p.id))});document.querySelectorAll(".card").forEach(x=>x.onclick=()=>openPlace(+x.dataset.id))}
function translate(){document.documentElement.lang=lang;document.querySelectorAll("[data-t]").forEach(x=>x.textContent=t(x.dataset.t));language.textContent=lang==="en"?"ES":"EN";search.placeholder=lang==="en"?"Search a place or city…":"Buscar lugar o ciudad…";fill();render();if(selected)openPlace(selected)}
function openPlace(id){let p=places.find(x=>x.id===id);selected=id;photo.style.background="linear-gradient(135deg,"+colors[p.category]+"44,#f8f5ed)";photo.innerHTML=p.image?'<img src="'+p.image+'" alt="'+(lang==="en"?p.name:p.es)+'"><span class="photo-badge">'+p.emoji+'</span>':'<span class="photo-fallback">'+p.emoji+'</span>';tag.textContent=categoryLabel(p.category);placeName.textContent=lang==="en"?p.name:p.es;location.textContent=p.city+" · "+p.department;description.textContent=lang==="en"?p.description:p.descripcion;wantBtn.textContent=want.has(id)?t("wanted"):t("wantBtn");visitedBtn.textContent=visited.has(id)?t("done"):t("mark");wantBtn.classList.toggle("active",want.has(id));visitedBtn.classList.toggle("active",visited.has(id));directions.href="https://www.google.com/maps/dir/?api=1&destination="+p.lat+","+p.lng;modal.classList.add("open");modal.setAttribute("aria-hidden","false");map.setView([p.lat,p.lng],Math.max(map.getZoom(),11))}
function close(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
language.onclick=()=>{lang=lang==="en"?"es":"en";localStorage.estgLang=lang;translate()};search.oninput=()=>{special="";render()};category.onchange=department.onchange=()=>{special="";render()};reset.onclick=()=>{special="";search.value="";category.value="";department.value="";render();map.setView([13.73,-88.87],8)};document.querySelectorAll("[data-close]").forEach(x=>x.onclick=close);document.onkeydown=e=>{if(e.key==="Escape")close()};wantBtn.onclick=()=>{want.has(selected)?want.delete(selected):want.add(selected);persist();openPlace(selected);render()};visitedBtn.onclick=()=>{visited.has(selected)?visited.delete(selected):visited.add(selected);persist();openPlace(selected);render()};wantFilter.onclick=()=>{special="want";render();document.querySelector("#explore").scrollIntoView()};visitedFilter.onclick=()=>{special="visited";render();document.querySelector("#explore").scrollIntoView()};total.textContent=places.length;counts();translate();loadImages();