const lang=document.documentElement.lang==="es"?"es":document.documentElement.lang==="fr"?"fr":"en";
const busRoutes=[
{from:"SAL Airport",fromEs:"Aeropuerto SAL",to:"San Salvador",mode:"public",route:"138",time:"50–75 min",fare:"$0.60–$1",terminal:"Airport access road / San Salvador",terminalEs:"Vía de acceso del aeropuerto / San Salvador",note:"Walk to the public stop outside the arrivals complex. Confirm the San Salvador direction before boarding.",noteEs:"Camina hasta la parada pública fuera del complejo de llegadas. Confirma la dirección a San Salvador antes de subir."},
{from:"SAL Airport",fromEs:"Aeropuerto SAL",to:"El Tunco / El Zonte",mode:"shuttle",route:"Shared shuttle",routeEs:"Transporte compartido",time:"45–75 min",fare:"$15–$25",terminal:"Pre-booked airport pickup",terminalEs:"Recogida reservada en el aeropuerto",note:"Convenient with luggage or a late arrival. Reserve with a verified operator before flying.",noteEs:"Conveniente con equipaje o llegada tardía. Reserva con un operador verificado antes de volar."},
{from:"San Salvador",fromEs:"San Salvador",to:"La Libertad",mode:"public",route:"102 / 102A",time:"45–75 min",fare:"$0.60–$1.50",terminal:"Central San Salvador → La Libertad",terminalEs:"Centro de San Salvador → La Libertad",note:"Route 102 serves La Libertad; some 102A services continue toward the surf coast. Confirm the final destination.",noteEs:"La ruta 102 llega a La Libertad; algunos servicios 102A continúan hacia la costa. Confirma el destino final."},
{from:"La Libertad",fromEs:"La Libertad",to:"El Tunco / El Zonte",mode:"public",route:"192",time:"25–50 min",fare:"$0.50–$1.50",terminal:"Coastal highway westbound",terminalEs:"Carretera del Litoral hacia occidente",note:"Ask for your beach by name and tell the fare collector where you need to get off.",noteEs:"Pregunta por la playa y dile al cobrador dónde necesitas bajarte."},
{from:"San Salvador",fromEs:"San Salvador",to:"Santa Ana",mode:"public",route:"201",time:"1.5–2 h",fare:"$1.50–$2.50",terminal:"Terminal de Occidente",terminalEs:"Terminal de Occidente",note:"Direct and special services may differ in comfort, stops and fare.",noteEs:"Los servicios directos y especiales pueden variar en comodidad, paradas y tarifa."},
{from:"San Salvador",fromEs:"San Salvador",to:"Suchitoto",mode:"public",route:"129",time:"1.25–1.75 h",fare:"$1–$2",terminal:"Terminal de Oriente / confirm current stop",terminalEs:"Terminal de Oriente / confirma la parada actual",note:"Depart early and confirm the last return bus before exploring the town.",noteEs:"Sal temprano y confirma el último bus de regreso antes de recorrer el pueblo."},
{from:"San Salvador",fromEs:"San Salvador",to:"Ruta de las Flores",mode:"public",route:"205 + 249",time:"2.5–3 h",fare:"About $2",fareEs:"Aprox. $2",terminal:"Terminal de Occidente → Sonsonate transfer",terminalEs:"Terminal de Occidente → transbordo en Sonsonate",note:"Take 205 to Sonsonate, then 249 toward Juayúa, Apaneca and Ataco.",noteEs:"Toma la 205 a Sonsonate y luego la 249 hacia Juayúa, Apaneca y Ataco."},
{from:"Santa Ana",fromEs:"Santa Ana",to:"Ruta de las Flores",mode:"public",route:"210 + 249",time:"1.5–2.5 h",fare:"$1–$2",terminal:"Santa Ana → Ahuachapán transfer",terminalEs:"Santa Ana → transbordo en Ahuachapán",note:"Take 210 to Ahuachapán, then 249 toward Ataco, Apaneca and Juayúa.",noteEs:"Toma la 210 a Ahuachapán y luego la 249 hacia Ataco, Apaneca y Juayúa."},
{from:"San Salvador",fromEs:"San Salvador",to:"San Miguel",mode:"public",route:"301",time:"2.5–3 h",fare:"$3–$5",terminal:"Terminal de Oriente / Plaza Amanecer",terminalEs:"Terminal de Oriente / Plaza Amanecer",note:"Choose a direct or special service when available and verify the current boarding terminal.",noteEs:"Elige servicio directo o especial cuando esté disponible y confirma la terminal actual."},
{from:"San Miguel",fromEs:"San Miguel",to:"El Cuco",mode:"public",route:"320",time:"1–1.5 h",fare:"About $1–$2",fareEs:"Aprox. $1–$2",terminal:"San Miguel bus terminal",terminalEs:"Terminal de buses de San Miguel",note:"Services are commonly reported about every 30 minutes during the day; verify the last departure.",noteEs:"Se reportan salidas aproximadamente cada 30 minutos durante el día; confirma la última salida."},
{from:"San Miguel",fromEs:"San Miguel",to:"La Unión",mode:"public",route:"324",time:"1–1.5 h",fare:"$1.50–$3",terminal:"San Miguel eastern terminal",terminalEs:"Terminal oriental de San Miguel",note:"Confirm the route number and whether the service enters central La Unión.",noteEs:"Confirma el número de ruta y si el servicio entra al centro de La Unión."},
{from:"San Salvador",fromEs:"San Salvador",to:"El Tunco / Santa Ana / Suchitoto",mode:"shuttle",route:"Shared shuttle",routeEs:"Transporte compartido",time:"45 min–1.5 h",fare:"$15–$30",terminal:"Hotel or agreed pickup point",terminalEs:"Hotel o punto de recogida acordado",note:"Best for travelers who prefer reserved seats, direct pickup and space for luggage.",noteEs:"Ideal para viajeros que prefieren asiento reservado, recogida directa y espacio para equipaje."}
];
const boardingPoints={
"138":{board:"Public bus stop for Route 138 outside SAL Airport",boardEs:"Parada pública de la Ruta 138 fuera del Aeropuerto SAL",query:"Parada Ruta 138 Aeropuerto Internacional de El Salvador"},
"Shared shuttle":{board:"Pre-arranged pickup in the airport arrivals area or at your hotel",boardEs:"Recogida previamente acordada en llegadas del aeropuerto o en tu hotel",query:"Aeropuerto Internacional de El Salvador Llegadas"},
"102 / 102A":{board:"Route 102/102A stop, 17 Avenida Sur near Cementerio Los Ilustres",boardEs:"Parada Ruta 102/102A, 17 Avenida Sur cerca del Cementerio Los Ilustres",query:"17 Avenida Sur Cementerio Los Ilustres San Salvador"},
"192":{board:"Coastal bus boarding area in La Libertad",boardEs:"Zona de abordaje de buses costeros en La Libertad",query:"Terminal de Buses Puerto de La Libertad"},
"201":{board:"Terminal de Occidente, San Salvador",boardEs:"Terminal de Occidente, San Salvador",query:"Terminal de Occidente San Salvador"},
"129":{board:"Terminal de Oriente (Plaza Amanecer)",boardEs:"Terminal de Oriente (Plaza Amanecer)",query:"Terminal de Oriente Plaza Amanecer Soyapango"},
"205 + 249":{board:"Terminal de Occidente — board Route 205",boardEs:"Terminal de Occidente — aborda la Ruta 205",query:"Terminal de Occidente San Salvador",transfer:"Terminal Sedas, Sonsonate — transfer to Route 249",transferEs:"Terminal Sedas, Sonsonate — transborda a la Ruta 249",transferQuery:"Terminal Sedas Sonsonate"},
"210 + 249":{board:"Terminal Municipal Francisco Lara Pineda, Santa Ana — board Route 210",boardEs:"Terminal Municipal Francisco Lara Pineda, Santa Ana — aborda la Ruta 210",query:"Terminal Municipal Francisco Lara Pineda Santa Ana El Salvador",transfer:"Route 249 roadside stop toward Ataco, near ISSS Ahuachapán",transferEs:"Parada de la Ruta 249 hacia Ataco, cerca del ISSS Ahuachapán",transferQuery:"ISSS Ahuachapan carretera hacia Concepcion de Ataco"},
"301":{board:"Terminal de Oriente (Plaza Amanecer) — Route 301 platforms",boardEs:"Terminal de Oriente (Plaza Amanecer) — plataformas de la Ruta 301",query:"Terminal de Oriente Plaza Amanecer Soyapango"},
"320":{board:"San Miguel bus terminal — ask for Route 320 to El Cuco",boardEs:"Terminal de buses de San Miguel — pregunta por la Ruta 320 a El Cuco",query:"Terminal de Buses San Miguel El Salvador"},
"324":{board:"San Miguel bus terminal — ask for Route 324 to La Unión",boardEs:"Terminal de buses de San Miguel — pregunta por la Ruta 324 a La Unión",query:"Terminal de Buses San Miguel El Salvador"}
};
function busModeLabel(mode){return mode==="public"?(lang==="es"?"Bus público":"Public bus"):(lang==="es"?"Transporte turístico":"Tourist shuttle")}
function busMapUrl(query){return "https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(query+", El Salvador")}
function boardingLinks(route){
 const point=boardingPoints[route.route];if(!point)return "";
 const boardLabel=lang==="es"?"Dónde abordar":"Where to board",transferLabel=lang==="es"?"Dónde transbordar":"Where to transfer";
 let output='<div class="boarding-point"><span>'+boardLabel+'</span><a href="'+busMapUrl(point.query)+'" target="_blank" rel="noopener">📍 '+(lang==="es"?point.boardEs:point.board)+' <b>OPEN MAP ↗</b></a></div>';
 if(point.transfer)output+='<div class="boarding-point transfer-point"><span>'+transferLabel+'</span><a href="'+busMapUrl(point.transferQuery)+'" target="_blank" rel="noopener">🔄 '+(lang==="es"?point.transferEs:point.transfer)+' <b>OPEN MAP ↗</b></a></div>';
 return output;
}
function renderBus(){
 const box=document.getElementById("busResults");if(!box)return;
 const q=document.getElementById("busSearch").value.toLowerCase().trim(),mode=document.getElementById("busMode").value;
 const list=busRoutes.filter(r=>(mode==="all"||r.mode===mode)&&(!q||[r.from,r.fromEs,r.to,r.route,r.terminal,r.terminalEs].join(" ").toLowerCase().includes(q)));
 box.innerHTML=list.map(r=>'<article class="bus-route"><div class="bus-route-top"><span class="mode '+r.mode+'">'+busModeLabel(r.mode)+'</span><strong>'+r.route.replace("Shared shuttle",lang==="es"?(r.routeEs||r.route):r.route)+'</strong></div><h3><a class="place-map-link" href="'+busMapUrl(lang==="es"?r.fromEs:r.from)+'" target="_blank" rel="noopener" title="'+(lang==="es"?"Abrir origen en Google Maps":"Open origin in Google Maps")+'">'+(lang==="es"?r.fromEs:r.from)+' <em>↗</em></a> <span>→</span> <a class="place-map-link" href="'+busMapUrl(r.to)+'" target="_blank" rel="noopener" title="'+(lang==="es"?"Abrir destino en Google Maps":"Open destination in Google Maps")+'">'+r.to+' <em>↗</em></a></h3><div class="route-facts"><span>⏱️ <b>'+r.time+'</b></span><span>💵 <b>'+(lang==="es"?(r.fareEs||r.fare):r.fare)+'</b></span></div>'+boardingLinks(r)+'<p>'+(lang==="es"?r.noteEs:r.note)+'</p></article>').join("")||'<p class="bus-empty">'+(lang==="es"?"No se encontraron rutas.":"No routes found.")+'</p>';
}


const busSearch=document.getElementById("busSearch"),busMode=document.getElementById("busMode");
if(busSearch)busSearch.oninput=renderBus;
if(busMode)busMode.onchange=renderBus;
renderBus();

